### ISSUE TITLE
Connection established, but everythings frozen

### ISSUE THREAD

**Issue by Liquidmasl** [IBM-Swift/BlueSSLService#1]
Hi

I got a connection between my server and client using a key chain, the server says the user is signed in, but the app is frozen completely.

The console just gives me..

`subsystem: com.apple.securityd, category: SecError, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 2, enable_private_data: 0`

but i think thats just xcode 8...

It doenst actually crash, its in some kind of frozen state.

If the server cancels the connection while "connected but frozen" i actually get a console output saying : `Error code: -9806, ERROR: SSLHandshake, code: -9806, reason: errSSLClosedAbort`

App still frozen

I am really out of any ideas now..
Any idea what went wrong?

EDIT:  i debuged my project and came to the conclusion that the app fleezes at this spot in SSLService.swift:

```

private func prepareConnection(socket: Socket) throws {

..

repeat {
			
			status = SSLHandshake(sslContext)
            
		} while status == errSSLWouldBlock

...

```

**Comment by billabt** [comment]
I take it you're using the 0.11.x master-next...  That's definitely experimental and relatively untested.  There's still quite a bit of work left to do on the Secure Transport side.  The 0.10.x on master is much more stable altho' it does use OpenSSL on both macOS and Linux.  If you can use that one for now, you'd probably see better results...

**Comment by billabt** [comment]
@Liquidmasl, I just released another version on 0.11.x master-next branch.  This should fix your problem.  Let me know if you have anymore issues.  Thanks again.

**Comment by Liquidmasl** [comment]
Thanks a lot!
I am actually pretty new to xcode and swift, i failed misrable trying to get the packages into xcode after loading them with packet manager, and had problems with those open ssl frameworks. I really just at the beginning.
Thanks! I will try the new implementation as soon as i get access to our server again

**Comment by Liquidmasl** [comment]
sadly not this isnt working anymore             

clientSocket?.delegate = try SSLService(usingConfiguration: config)

cant use service as a delegate, if i use as! SSLServiceDelegate it throws a lot more errors my way..

**Comment by billabt** [comment]
New more information.  What version of BlueSSLService are you using?  Also, what errors are you seeing?  Finally, what version of Xcode are you using?

**Comment by Liquidmasl** [comment]
i just now downloaded the new blueSSL service from github, and i run the xcode 8.0 GM version right now.

The error i see is " Cannot assign value of type 'SSLService?' to type 'SSLServiceDelegate?'"

If I add a as! SSLServiceDelegate! i get Apple Match-O Linker errors.

<img width="442" alt="screen shot 2016-09-16 at 15 28 22" src="https://cloud.githubusercontent.com/assets/10048306/18587444/63335bc8-7c22-11e6-8ef3-3fefeced0ea1.png">


But as i said i am preeetty new to XCode. So this very well might be a mistake on my side while "updating" the server. I will try it on a new project. Just to be sure.

Thanks a lot, and sorry for the unprofessional inconvenience.

**Comment by billabt** [comment]
Can you show me a bit more of your code?  Also, are you downloading from master or master-next?  The problem looks like the way you're assigning the delegate but I can't tell without seeing more of your code.  Thanks.

**Comment by Liquidmasl** [comment]
Yes i sure can, its not a lot more, the whole project is nothing but a "get the ssl thing working"-testproject.


`
import UIKit

import Socket
import SSLService

class ViewController: UIViewController {
    
    var clientSocket: Socket?
    
    let serverCertPath = "/Users/Marcel1/Documents/Programmieren privat/SSLverzweilfung/SSLverzweilfung/cert.pem"
    let privateCertPath = "/Users/Marcel1/Documents/Programmieren privat/SSLverzweilfung/SSLverzweilfung/privateKey.pem"
    
    
    let config = SSLService.Configuration(withChainFilePath: "/Users/Marcel1/Documents/Programmieren privat/SSLverzweilfung/SSLverzweilfung/certificateMaybeChain.p12", usingSelfSignedCerts: true, withPassword: "*********")
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
   
        
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    
    @IBAction func sendSomethingButtonPressed(_ sender: AnyObject) {
        
        
        if clientSocket == nil ||  clientSocket?.isConnected == false{
            
                connection()
            
        }
        
        if clientSocket != nil {
            if (clientSocket?.isConnected)!{
                send(message: "LOL")
                
                
            } else{
                print("no connection astablished")
            }
        } else {
            print("no socket created")
        }
    }
    

    func send(message: String){
        do {
            try clientSocket!.write(from: message)
        } catch let error {
            
            guard let socketError = error as? Socket.Error else {
                
                print("Unexpected error...")
                return
            }
            
            print("Error reported:\n \(socketError.description)")
            
        }
    }
    
    
    
    func connection(){
        
        do {
            
            // Create an IPV4 socket...
            try self.clientSocket = Socket.create()
            
            
            guard self.clientSocket != nil else {
                
                print("Unable to unwrap socket...")
                return
            }
            
            
            try clientSocket?.setBlocking(mode: false)
            
            clientSocket?.delegate = try SSLService(usingConfiguration: config) as! SSLServiceDelegate
            
            print("connecting...")
            try clientSocket!.connect(to: "192.168.1.22", port: 9999)
            print("connected!!")
            
        } catch let error {
            
            guard let socketError = error as? Socket.Error else {
                
                print("Unexpected error...")
                print(error)
                return
            }
            
            print("Error reported:\n \(socketError.description)")
            
            
            
        }
    }
    
}

`

**Comment by billabt** [comment]
First of all, you don't need the `as! SSLServiceDelegate`.  Take that out.  Next, what version of the *BlueSSLService* are you using? 0.11.16 or 0.10.18?  Judging by your code, you're probably using 0.11.16 but an older version.  The signature for configuration init function you're using changed...
You have:
```
let config = SSLService.Configuration(withChainFilePath: "/Users/Marcel1/Documents/Programmieren privat/SSLverzweilfung/SSLverzweilfung/certificateMaybeChain.p12", usingSelfSignedCerts: true, withPassword: "*********")
```
It should be:
```
let config = SSLService.Configuration(withChainFilePath: "/Users/Marcel1/Documents/Programmieren privat/SSLverzweilfung/SSLverzweilfung/certificateMaybeChain.p12", withPassword: "*********", usingSelfSignedCerts: true)
```
If you're using the latest version...

Finally, you should upgrade to released version of Xcode 8.  The toolchain included in that version is the latest and is what you should be using...

Once you've done that and confirmed that you're running the latest code, let me know how you make out.  Hope this helps.

**Comment by Liquidmasl** [comment]
It does help a lot, thank you!
I will keep you posted. thanks a lot, really!

**Comment by Liquidmasl** [comment]
Sorry for the slowness, univercity started again, time is running low!

Sadly i am just to stupid to even get the framework into xcode. He just doesnt want my "include SSLService".

Last time I did it after 8 houres of failing so I will need some time to get this going sadly.

**Comment by Liquidmasl** [comment]
Hi, sorry for the huge delay, university started again, time ran low.

Sadly I am not able to even get the framework into X-Code.
Last time i spent over 10 houres to get it going, because I dont really know how to do it right, and i dont find any conclusive guide.
Whatever I do:

"No such module 'SSLService'"

Last time i did the same thing over and over again until it kinda worked.

I know its far from your job or concern, but could you maybe give me a tip o how to do it right? Or maybe you know a source where i can learn?

eG.: is there a Way to get the Packages downloaded with the "package manager" easy into xcode?

The only thing i managed was to download the git as zip from the git homepage, and pull the folder into xcode.
Or just pull the xcodeProj into xcode, then link the binaries.
Or should i download with package manager and then pull into xCode?
If i should use the package manager, how do i start? Just write a .Package file with the SSLservice git URL? or do i use the .package file you deliver with the SSLService?

<img width="662" alt="screen shot 2016-10-04 at 11 19 32" src="https://cloud.githubusercontent.com/assets/10048306/19068843/8acc3c62-8a24-11e6-8f05-2361fed46dce.png">

Sorry if i sound kind of desperate, but thats because I am.
Something THAT trivial probably is THAT easy. But i am missing something.
I spent about 12 houres just trying to get frameworks running in xCode. I feel like the worst informatics student on this rock.

I hope you can help me out somehow.
Greetings

**Comment by Liquidmasl** [comment]
<img width="872" alt="screen shot 2016-10-04 at 11 44 58" src="https://cloud.githubusercontent.com/assets/10048306/19069676/1c41810e-8a28-11e6-9275-a77838704f7e.png">



Also i get this. 
All those files are there, and referenced, i can even look at them from inside xcode, i dont know what his problem is. 
Cant figure out last line though.

**Comment by billabt** [comment]
Try this:
1. Open a terminal. 
2. Make a directory using your executable as the directory name and cd to it. For example:
```
mkdir MyExecutable
```
3. Create your Swift project.
```
swift package init --type executable
```
4. Edit *Package.swift* and add the dependency on *BlueSSLService* and save it. 
5. Do a build to make sure your edits to *Package.swift* are correct. Do your build as follows:
```
swift build 
```
6. Now create the Xcode project using the following command:
```
swift package generate-xcodeproj 
```
7. Open the generated Xcode project. 
8. Happy coding.

**Comment by Liquidmasl** [comment]
Thank you very very much, I did all this.

But still...
I get that i do not need the Socket include, kindof. But he still doesnt like the SSL part of things.

If thats the way to add Frameworks to xcode, how can i add frameworks to existing projects? 



<img width="167" alt="screen shot 2016-10-04 at 17 41 09" src="https://cloud.githubusercontent.com/assets/10048306/19081291/103980f0-8a5a-11e6-8edc-971a35f2cdba.png">
<img width="259" alt="screen shot 2016-10-04 at 17 40 31" src="https://cloud.githubusercontent.com/assets/10048306/19081293/105c5e72-8a5a-11e6-8778-87424fa69b1a.png">
<img width="259" alt="screen shot 2016-10-04 at 17 41 16" src="https://cloud.githubusercontent.com/assets/10048306/19081294/105d0408-8a5a-11e6-83c2-8849c8316f99.png">

**Comment by billabt** [comment]
I tried all the steps I sent you and got a working Xcode project.  I can't help you anymore without seeing your project.  If you want to zip up the directory with the project in it, I'll try and take a look at it.

**Comment by Liquidmasl** [comment]
You are so kind. 
I actually feel a bit bad to take your time, but thanks!

[blueSSLagain.zip](https://github.com/IBM-Swift/BlueSSLService/files/508957/blueSSLagain.zip)


If you are coming to vienna once i will take you out for a lunch! Or a coffee.. or beer..
Thanks so much for your effort!

**Comment by Liquidmasl** [comment]
I just saw that my target membership was off a bit, it seems my view controller now actually takes everything! 

Just one error left right now, in the "SSLService.swift" file it cant find the module "Socket"

The SSLService target hat Socket as dependency and as a linked binary..

**Comment by billabt** [comment]
I cleaned up the project.  It now builds (on macOS) from both the command line and via Xcode.  You seem to want to turn this into a iOS project.  To do that, you'll have to *modify* both the  Socket and SSLService targets to build **iOS frameworks instead of macOS ones**.  Then you can add a **new** iOS target and add Socket and SSLService targets as dependencies to the **new** iOS target you added.

Here's my fixed version of your project --> 
[blueSSLagain.zip](https://github.com/IBM-Swift/BlueSSLService/files/509069/blueSSLagain.zip)

Remember, right now this project only builds on **macOS**.

**Comment by Liquidmasl** [comment]
thanks again!

Oh okay, i kind of missed that, yeah its meant to become an ios project. I will get reading into the target system, thanks a lot. 
In the process i actually learned a lot!

Thanks!
Greetings from vienna

**Comment by Liquidmasl** [comment]
I got it working on macOS!
This is so much joy right now!

I also tried to get it going on iOs, I added an ios target and added Socket and SSLService to dependencies, I also changed the supported platform from those two to iOs

But as soon as i changed the module platforms to ios i got my "No such module "Socket"
and also I got another error:

<img width="1137" alt="screen shot 2016-10-06 at 23 05 45" src="https://cloud.githubusercontent.com/assets/10048306/19170846/3d515d80-8c1a-11e6-900b-1deef480c1cb.png">

**Comment by billabt** [comment]
Great news!!!  Send me the project again and I'll see if I can figure out why it can't find the *Socket* module. The other error is a result of differences in the definition of `SSLCipherSuite` on macOS versus iOS.  It's a `UInt32` on macOS and a `UInt16` on iOS.  I've checked in a fix and released a new version.

**Comment by Liquidmasl** [comment]
I am sorry again i was pretty much done with univercity again.. sad when there is to less time for personal projects ):

I got it here... strangely i cant even run to the mac target right know because he tries to build the ios files.. I dont get why it should not do that..

I am so glad you help me out, thanks a lot!

[blueSSLagainwithIOS.zip](https://github.com/IBM-Swift/BlueSSLService/files/536864/blueSSLagainwithIOS.zip)

**Comment by billabt** [comment]
I'll try to take a look at it over the weekend...

**Comment by Liquidmasl** [comment]
whenever you can, thanks a lot..

**Comment by Liquidmasl** [comment]
i actually just updated the dependancies and it works just like that now :O

**Comment by dmitrykurochka** [comment]
Hi! I have tried new version.
Now 465 port is working ok,
but I could not get worked 587  port either by useTLS: true or useTLS: false
Do you have any ideas?
