### ISSUE TITLE
SecPKCS12Import bottleneck for acceptance from a listening socket

### ISSUE THREAD

**Issue by na-gupta** [IBM-Swift/BlueSSLService#11]
Testing Kitura with SSLService causes a significant slowdown on osx (but not on linux). On investigating, it appears that SecPKCS12Import() (that runs every time a listening socket accepts a connection and initializes it's delegate) is very expensive. If we cache and reuse the pkcs12 certs in SSLService.Configuration we get a significant performance increase.

Testing this change with wrk shows a performance improvement from about 150 Requests/sec to about 5200 Requests/sec (35x improvement). It still is much slower than without SSL (24k Requests/sec).

On linux, using OpenSSL, the performance is comparable to without SSL. So there are probably other areas of potential improvement.

I will submit a pull request with my changes.

**Comment by na-gupta** [comment]
<img width="1007" alt="screen shot 2017-01-18 at 2 52 24 pm" src="https://cloud.githubusercontent.com/assets/12917107/22084791/087ca7bc-dd97-11e6-9dd5-e161749e63eb.png">

**Comment by billabt** [comment]
Fixed in 0.12.17.
