### ISSUE TITLE
SIGPIPE when SSL clients disconnect

### ISSUE THREAD

**Issue by djones6** [IBM-Swift/BlueSSLService#13]
I'm seeing a similar issue with SSL connections to the one seen in regular (unsecured) connections in IBM-Swift/BlueSocket#48 - when my workload driver (`wrk`) shuts down at the end of the testing period, Kitura almost always terminates with RC 141 (which is `SIGPIPE`).

Although Socket is used to create the sockets, on Linux the `SO_NOSIGPIPE` option is not available, so we instead set `MSG_NOSIGNAL` each time we write to the socket.

In the case of SSLService, writes are performed via `SSL_write()` which does not provide a facility to set this flag.  The remaining option is to receive but ignore the SIGPIPE signal.

**Comment by billabt** [comment]
Ignoring a OS signal is an *application* decision. By adding an ignore of the **SIGPIPE** signal to *BlueSSLService* we are introducing a *potential unwanted side effect* to the application using the framework.  There could be instances where the application is expecting the **SIGPIPE** and plans to handle it.  If a framework were to inhibit the signal, this would adversely affect the application. At present, the **SIGPIPE** only appears to be happening your test case.  Put the ignore at the beginning of your application should solve the problem.  This signal is *NOT* appearing in any of the *Kitura* tests so it could be the result of the way you're exercising the framework in your workload driver.  Adding an ignore of the signal in the *BlueSSLService* framework is *NOT* an appropriate solution.

**Comment by billabt** [comment]
If you wanted to explore why you're getting the *SIGPIPE* in your test case, you add a signal handler in your *main.swift* file and when the signal is raised, call ```fatalError("Caught Signal")``` and get a stack trace to see what code path caused the signal to be raised...

This can be done easily using *BlueSignals* as shown below...
```
...
import Signals
...

Signals.trap(signal: .pipe) {
    fatalError("Caught SIGPIPE")
}

...
< Rest of main.swift >
```
