### ISSUE TITLE
Which key/cert is which?

### ISSUE THREAD

**Issue by Liquidmasl** [IBM-Swift/BlueSSLService#15]
this is not really an issue with the project but with my understanding of it.

We are trying to figure out where to get which keys and certificates.

We guess the client needs the server certificate, and the client needs its own keypair? 

we are overwhelmed by the configuration possibilities and dont get the differences or advantage/disadvatage of the different methods.

Out server implementation is not made with this framework, which does not make things easier..

what is the CAcertificateFilePath/Directory and why can you set it to nil?

can we just configure with just the server cert and nil as CAcert like this?
`SSLService.Configuration(withCACertificateFilePath: nil, usingCertificateFile: serverCert)`

Or do i need to take this method with a clientsided generated private key and certificate? or clientsided key but server cert?
`SSLService.Configuration(withCACertificateFilePath: nil, usingCertificateFile: serverCert, withKeyFile: clientPrivateKey, usingSelfSignedCerts: true)`

Also in the desciption it states that .pem files are needed for all keys and certs, but i always get this error: PKCS12 file not specified.
what does this mean? 

thanks in advance, i hope someone can shine a little light in my confusion

Our setup: Our server has created a self signed certificate, this certificate is available for the app to use to be able to connect to the server. 
Where do i put it? is this the desired cert part?
is the CAcert the same as the server cert? since it is self signed?

what are these private keys? does the client need a keypair before connecting?

**Comment by gtaban** [comment]
Hi @Liquidmasl 
For some basics of SSL setup, please see:
https://developer.ibm.com/swift/2016/09/22/securing-kitura-part-1-enabling-ssltls-on-your-swift-server/

The above should show you how to build a server that supports SSL.  You can connect to this server using browser as the blog shows. You can also build your own client such as an iOS app and you can follow online tutorials for that. In general case, certificates are not needed for clients unless you want mutual authentication which is really for specific use cases.

Goodluck!
