### ISSUE TITLE
Cannot compile v0.12.25 on linux (Ubuntu 14.04).

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/BlueSSLService#18]
app_1  | Compile Swift Module 'SSLService' (1 sources)
app_1  | /usr/include/openssl/bn.h:187:19: error: integer literal is too large to be represented in any integer type
app_1  | #define BN_MASK         (0xffffffffffffffffffffffffffffffffLL)
app_1  |                          ^
app_1  | /root/Kitura-Starter/Packages/SSLService-0.12.25/Sources/SSLService.swift:817:31: error: use of unresolved identifier 'SSL_CTRL_SET_ECDH_AUTO'
app_1  |                                 SSL_CTX_ctrl(context, SSL_CTRL_SET_ECDH_AUTO, 1, nil)
app_1  |                                                       ^~~~~~~~~~~~~~~~~~~~~~
app_1  | OpenSSL.SSL_CTRL_SET_READ_AHEAD:1:12: note: did you mean 'SSL_CTRL_SET_READ_AHEAD'?
app_1  | public var SSL_CTRL_SET_READ_AHEAD: Int32 { get }
app_1  |            ^
app_1  | OpenSSL.SSL_CTRL_SET_SRP_ARG:1:12: note: did you mean 'SSL_CTRL_SET_SRP_ARG'?
app_1  | public var SSL_CTRL_SET_SRP_ARG: Int32 { get }
app_1  |            ^
app_1  | <unknown>:0: error: build had 1 command failures
app_1  | swift-build: error: exit(1): /root/swift-3.0.2-RELEASE-ubuntu14.04/usr/bin/swift-build-tool -f /root/Kitura-Starter/.build/debug.yaml
kiturastarter_app_1 exited with code 1
Ricardos-MacBook-Pro:Kitura-Starter olivieri$

**Comment by rolivieri** [comment]
Looks like we now custom flags to compile on linux: swift build -Xswiftc -DOPENSSL_TOO_OLD.

I will update the swift starter app on bluemix as well.

**Comment by rolivieri** [comment]
I updated Kitura-Starter, added the new compilation flags, updated docker-compose file, and tested the app on Bluemix. Buildpack was able to provision the app. I will merge the changes to the master branch (Kitura-Starter) once the build passes on Bluemix. Closing this issue since the issue was due to the need of passing custom compilation flags: swift build -Xswiftc -DOPENSSL_TOO_OLD.

**Comment by rolivieri** [comment]
This change will affect all of our sample apps. Maybe we should have tagged this new version of BlueSSLService library by increasing the major number?

**Comment by shmuelk** [comment]
This has broken everyone who uses BlueSSLService on Ubuntu 14.04, this includes all Kitura users. 

Adding a compile flag is **not** the way to fix this.
