### ISSUE TITLE
Compile 'SSLService' problem: bn.h:187:19: error: integer literal is too large to be represented in any integer type

### ISSUE THREAD

**Issue by qiyaod** [IBM-Swift/BlueSSLService#19]
The following problem blocked our pushing swift application to Bluemix:

STG/0
Compile Swift Module 'SSLService' (1 sources)
Mar 7, 2017 11:41:08 AM
STG/0
/tmp/app/.apt/usr/include/openssl/bn.h:187:19: error: integer literal is too large to be represented in any integer type
Mar 7, 2017 11:41:11 AM
STG/0
^
Mar 7, 2017 11:41:11 AM
STG/0
^~~~~~~~~~~~~~~~~~~~~~
Mar 7, 2017 11:41:11 AM
STG/0
SSL_CTX_ctrl(context, SSL_CTRL_SET_ECDH_AUTO, 1, nil)
Mar 7, 2017 11:41:11 AM
STG/0
#define BN_MASK (0xffffffffffffffffffffffffffffffffLL)
Mar 7, 2017 11:41:11 AM
STG/0
OpenSSL.SSL_CTRL_SET_READ_AHEAD:1:12: note: did you mean 'SSL_CTRL_SET_READ_AHEAD'?
Mar 7, 2017 11:41:11 AM
STG/0
public var SSL_CTRL_SET_READ_AHEAD: Int32 { get }
Mar 7, 2017 11:41:11 AM
STG/0
^
Mar 7, 2017 11:41:11 AM
STG/0
^
Mar 7, 2017 11:41:11 AM
STG/0
public var SSL_CTRL_SET_SRP_ARG: Int32 { get }
Mar 7, 2017 11:41:11 AM
STG/0
/tmp/app/Packages/SSLService-0.12.25/Sources/SSLService.swift:817:31: error: use of unresolved identifier 'SSL_CTRL_SET_ECDH_AUTO'
Mar 7, 2017 11:41:11 AM
STG/0
OpenSSL.SSL_CTRL_SET_SRP_ARG:1:12: note: did you mean 'SSL_CTRL_SET_SRP_ARG'?
Mar 7, 2017 11:41:11 AM
STG/0
<unknown>:0: error: build had 1 command failures
Mar 7, 2017 11:41:21 AM
STG/0
Failed to compile droplet
Mar 7, 2017 11:41:21 AM
STG/0
Exit status 223
Mar 7, 2017 11:41:21 AM
STG/0
Staging failed: Exited with status 223
Mar 7, 2017 11:41:21 AM
STG/0
Destroying container
Mar 7, 2017 11:41:21 AM
API/0
Failed to stage application: staging failed
Mar 7, 2017 11:41:21 AM
STG/0
swift-build: error: exit(1): /tmp/cache/swift-3.0.2/swift-3.0.2-RELEASE-ubuntu14.04/usr/bin/swift-build-tool -f /tmp/app/.build/release.yaml
Mar 7, 2017 11:41:21 AM
STG/0
Successfully destroyed container

**Comment by tunniclm** [comment]
We are also seeing this problem hitting in our Travis tests on Linux. There are two errors, one to do with the literal and one to do with an unresolved identifier.

```
/usr/include/openssl/bn.h:187:19: error: integer literal is too large to be represented in any integer type

#define BN_MASK         (0xffffffffffffffffffffffffffffffffLL)

                         ^

/tmp/87c06c14666f7ad8d15dbe70e37233d0b50cc764/notes/Packages/SSLService-0.12.25/Sources/SSLService.swift:817:31: error: use of unresolved identifier 'SSL_CTRL_SET_ECDH_AUTO'

                                SSL_CTX_ctrl(context, SSL_CTRL_SET_ECDH_AUTO, 1, nil)

                                                      ^~~~~~~~~~~~~~~~~~~~~~

OpenSSL.SSL_CTRL_SET_READ_AHEAD:1:12: note: did you mean 'SSL_CTRL_SET_READ_AHEAD'?

public var SSL_CTRL_SET_READ_AHEAD: Int32 { get }

           ^

OpenSSL.SSL_CTRL_SET_SRP_ARG:1:12: note: did you mean 'SSL_CTRL_SET_SRP_ARG'?

public var SSL_CTRL_SET_SRP_ARG: Int32 { get }

           ^

<unknown>:0: error: build had 1 command failures

error: exit(1): /home/travis/build/IBM-Swift/generator-swiftserver/swift-3.0-RELEASE-ubuntu14.04/usr/bin/swift-build-tool -f /tmp/87c06c14666f7ad8d15dbe70e37233d0b50cc764/notes/.build/debug.yaml

      1) "before all" hook
```

I see that this file has been added `.swift-build-linux`:
```
swift build -Xswiftc -DOPENSSL_TOO_OLD
```

If adding that option to swift build resolves the problem, then it looks like we have added a requirement to pass an option to any project that uses Kitura. :(

**Comment by shmuelk** [comment]
I agree with @tunniclm that adding a compile flag is **not** the way to fix this.

**Comment by billabt** [comment]
Removed the compile flag for the default.  The compile flag still exists in a different form.  It needs to be explicitly set to enable the functionality and this is documented in the README.md.  The functionality is provided by OpenSSL 1.0.2 or higher, this rules out use of it on Ubuntu 14.04.
