### ISSUE TITLE
Build fail on Linux (wrong OpenSSL version?)

### ISSUE THREAD

**Issue by niklassaers** [IBM-Swift/BlueSSLService#35]
Ca July 10th my Linux build of BlueSSLService started to fail: "swift build" fails with:

/usr/include/openssl/bn.h:189:28: error: integer literal is too large to be represented in any integer type
\#  define BN_MASK         (0xffffffffffffffffffffffffffffffffLL)
SSLService.swift:848:4: error: use of unresolved identifier 'SSL_CTX_setAutoECDH'
SSLService.swift:951:4: error: use of unresolved identifier 'SSL_CTX_set_alpn_select_cb_wrapper'
SSLService.swift:1156:4: error: use of unresolved identifier 'SSL_get0_alpn_selected_wrapper'

To be sure there are no out-of-date dependencies, I've run "sudo apt-get update; sudo apt-get upgrade" and rerun the build, but same error. The version of openssl is "1.0.2g-1ubuntu4.8"

Any idea why I get the error from OpenSSL and unresolved identifiers?

**Comment by billabt** [comment]
Update your Swift packages.

**Comment by niklassaers** [comment]
Thanks :-)
