### ISSUE TITLE
Missing documentation and example for client use

### ISSUE THREAD

**Issue by steamonimo** [IBM-Swift/BlueSSLService#37]
One big issue with Swift on Linux is that the the module "security" can not be used (it does not exist). Therefore URLSession can not be used with an URLDessionDelegate.

Can this client use be achieved with the BlueSSLService? So far I have only seen examples for the server side.

If this is possible it would be helpful to have an example in the documentation. In this example the BlueSSLService would be used like URLSession.dataTask to get data from a remote server via SSL.

**Comment by Lupurus** [comment]
That's true. I'm struggling with creating a threaded client, that can listen and send simultaneously. Do you have a solution?

**Comment by billabt** [comment]
Used in conjunction with _BlueSocket_ (i.e. creating a client Socket), you should be able to accomplish it.  However, bear in mind that this and _BlueSocket_ are **very low-level** libraries.  You'd have to do the majority of the work that's handled by URLSession yourself.
