### ISSUE TITLE
Write to socket error

### ISSUE THREAD

**Issue by benedictdelfierro** [IBM-Swift/BlueSSLService#4]
Tried to enable TLS by following sample from kitura.io in linux

but encountered this error when accesing the server

ERROR: handleWriteHelper() IncomingSocketHandler.swift line 194 - Write to socket (file descriptor 10 failed. Error number=0. Message=Success.

**Comment by billabt** [comment]
I've referred this to the Kitura team.  So far I've not been able to determine a reason for this failure in either *BlueSSLService* or *BlueSocket*.  Will let you know if I find out anything further.  Thanks.

**Comment by billabt** [comment]
Just a quick update, so far we've been unable to reproduce the error.  However, it has uncovered a few flaws in the way we're handling some errors and those are being fixed.

**Comment by billabt** [comment]
Unable to reproduce this.  Please reopen or open a new issue if you can find a reproduction scenario.  Thanks.
