### ISSUE TITLE
Duplicate: "Unable to fetch BlueSSLService #23"

### ISSUE THREAD

**Issue by leanne63** [IBM-Swift/BlueSSLService#41]
Since late last week, I've been unable to fetch BlueSSLService - or maybe something after it? I have the exact situation described at the closed [issue #23: Unable to fetch BlueSSLService](https://github.com/IBM-Swift/BlueSSLService/issues/23).

My Package.swift looks like:

````
import PackageDescription
let package = Package(
	name: "KituraAPI",
	targets: [],
	dependencies: [
		.Package(url: "https://github.com/IBM-Swift/Kitura.git", majorVersion: 1, minor: 7),
		.Package(url: "https://github.com/IBM-Swift/HeliumLogger.git", majorVersion: 1, minor: 7),
		.Package(url: "https://github.com/IBM-Swift/Swift-SMTP.git", Version(1,1,2)),
	]
)
````

`swift build` never gets past BlueSSLService:

````
$ swift build
Fetching https://github.com/IBM-Swift/Kitura.git
Fetching https://github.com/IBM-Swift/HeliumLogger.git
Fetching https://github.com/IBM-Swift/Swift-SMTP.git
Fetching https://github.com/IBM-Swift/Kitura-net.git
Fetching https://github.com/IBM-Swift/SwiftyJSON.git
Fetching https://github.com/IBM-Swift/Kitura-TemplateEngine.git
Fetching https://github.com/IBM-Swift/LoggerAPI.git
Fetching https://github.com/IBM-Swift/BlueSocket.git
Fetching https://github.com/IBM-Swift/CCurl.git
Fetching https://github.com/IBM-Swift/BlueSSLService.git
````

The Terminal title bar keeps flashing as though something is looping. I can't tell what the text is changing between, though, if it is indeed changing...

I'm on MacOS Sierra 10.12.6, using Swift 3.1:

````
Apple Swift version 3.1 (swiftlang-802.0.53 clang-802.0.42)
Target: x86_64-apple-macosx10.9
````

Hmm... maybe a `Target` issue?

Just guessing here, as it seems others have been able to use it recently judging by the most recent issue reports...

**Comment by billabt** [comment]
I haven't been able to reproduce that here.  Try opening an issue with Kitura itself.  It may have something to do with some of the Swift 4 changes that are going in.

**Comment by leanne63** [comment]
For anyone who comes here later: my particular issue was caused by an invalid tag in Swift-SMTP.

To troubleshoot, I used `swift build -v`, which gives a (very) verbose listing of what's happening in the build process. It was indeed looping, trying to fulfill the version dependency but blocked by the invalid tag.

**Comment by DMeechan** [comment]
@leanne63 Did you find a way to fix the invalid tag issue with Swift-SMTP? I'm getting the same looping problem when trying to retrieve dependencies.

**Comment by leanne63** [comment]
Yes, @DMeechan, the tag issue has been fixed in the repo. At your end, delete the `.build` folder, the `Packages` folder, if present, and the `Package.pins` file. Then, redo your `swift build` command. It should work now!

**Comment by anibalrodriguez** [comment]
check also for the major version, then delete .build and try `swift build` again.
