### ISSUE TITLE
EllipticCurve Ciphers Support iOS

### ISSUE THREAD

**Issue by pavanvalluru** [IBM-Swift/BlueSSLService#43]
Using EllipticCurveCiphers(for ex: **TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384**) is not working at least on iOS. Always results in SSLHandshake Error when using CipherSuites.

`let enabledCipherSuites = "C024,C02C"
            var config = SSLService.Configuration(withCipherSuite: enabledCipherSuites, clientAllowsSelfSignedCertificates: false)
            config.useDefaultCiphers = false
            blueSocketInstance.delegate = try SSLService(usingConfiguration: config)`

If I don't set SSLService delegate on BlueSocket instance, then the SSLHandshake works. If the delegate is set with BlueSSLService(like above) then SSLHandshake fails.

**Comment by billabt** [comment]
Try using the _default_ configuration for the cipherSuites by not setting your own.  The defaults should have the ciphers you need enabled.  If not, please re-open the issue and I'll treat it as a **bug**.  Thanks.
