### ISSUE TITLE
Failing build under Linux

### ISSUE THREAD

**Issue by thevojacek** [IBM-Swift/BlueSSLService#58]
It is not possible to build an Kitura application under Linux using IBM`s Linux docker (Ubuntu 14.04 and Swift 4.2) when BlueSSLService is included alongside Kitura.

Interestingly enough, theres no problem on macOS, probably related to a fact that some of the Kitura packages uses `OpenSSL` only for Linux builds.

Output:
`
'OpenSSL' /root/VojacekJan/.build/checkouts/OpenSSL.git-8485872258080618489: warning: Ignoring declared target(s) 'OpenSSL' in the system package
error: multiple targets named 'OpenSSL' in: OpenSSL, SSLService
`

Packages:
`
import PackageDescription

let package = Package(
    name: "Name",
    products: [
        .executable(name: "Name", targets: ["Name"]),
    ],
    dependencies: [
        .package(url: "https://github.com/IBM-Swift/Kitura.git", from: "2.5.3"),
        .package(url: "https://github.com/IBM-Swift/HeliumLogger", from: "1.7.1"),
        .package(url: "https://github.com/IBM-Swift/Kitura-Session.git", from: "3.2.0"),
        .package(url: "https://github.com/thevojacek/Kitura-MiniHandlebars", from: "1.2.2"),
        .package(url: "https://github.com/OpenKitten/MongoKitten", from: "4.1.3"),
        .package(url: "https://github.com/thevojacek/Kitura-MongoDbSessionStore", from: "0.2.2"),
        .package(url: "https://github.com/IBM-Swift/Swift-JWT", from: "2.0.0"),
        .package(url: "https://github.com/krzyzanowskim/CryptoSwift", from: "0.12.0")
    ],
    targets: [
        .target(
            name: "Name",
            dependencies: [
                "Kitura",
                "HeliumLogger",
                "Kitura-MiniHandlebars",
                "KituraSession", "MongoKitten",
                "Kitura-MongoDbSessionStore",
                "SwiftJWT",
                "CryptoSwift"
            ]),
    ]
)
`

Any help is much appreciated.

**Comment by thevojacek** [comment]
I did. I made sure i am on the newest versions possible. Even tried to delete "./build" several times and to completely re-build all of the packages. Result is still the same.

**Comment by billabt** [comment]
Probably some packages in Kitura haven’t been updated yet. Open an issue against Kitura and they can take a look. There were still changes going on yesterday afternoon.

**Comment by thevojacek** [comment]
Ok thanks, i will do.

**Comment by djones6** [comment]
Apologies, it turns out that the Swift 4.2 system library targets cannot have the same name as another package from another dependency (or, more surprisingly, a system library target declared in another dependency).

I've pushed through #59 which should hopefully fix this and I'm discussing with the SwiftPM folks as to whether this is expected behaviour or a bug.  Please can you try updating to the latest packages (BlueSSLService `1.0.21` and BlueCryptor `1.0.12`) and see if the problem is resolved?

**Comment by thevojacek** [comment]
I have just tried that and it works! Thanks for your help.
Can i expect, that version 1.0.21 of BlueSSLService will be updated as dependency of other packages as well?
