### ISSUE TITLE
No such module 'SSLService'

### ISSUE THREAD

**Issue by namanzetrixweb** [IBM-Swift/BlueSSLService#71]
Hello , 
My Application wants to user smtp service to send mail. 
i have created package.swift file and add all the dependencies . It is not giving me any error. 
but when i build my project . It is giving me this error : "No such module 'SSLService'" .When i try to import sslservice .
Please guide me through process .

**Comment by billabt** [comment]
Can you please upload your Package.swift file?  Thanks.

**Comment by namanzetrixweb** [comment]
Sure Here it is. 


[Package.swift.zip](https://github.com/IBM-Swift/BlueSSLService/files/2867915/Package.swift.zip)

**Comment by billabt** [comment]
Add BlueSSLService to your Package.swift as a dependency.  Also, I noted you're using an old version of BlueSocket and BlueCrytor if using an older Swift version...  You should be able to use the latest versions for any version of Swift greater than 4.0.
